### ISSUE TITLE
2023-01-17版本卡logo

### ISSUE THREAD

**Issue by aimuch** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#10]
你好，
最新的版本，更换EFI以后卡logo:
- 配置不同之处：cpu是8700T,和32G内存，其他一样；
- 更改的操作：三码替换，重命名plist->config.plist

**Comment by aimuch** [comment]
> 你好， 最新的版本，更换EFI以后卡logo:
> 
> * 配置不同之处：cpu是8700T,和32G内存，其他一样；
> * 更改的操作：三码替换，重命名plist->config.plist

已解决，grubshell设置了下

**Comment by lyseky** [comment]
怎么设置？
