### ISSUE TITLE
你好能分享下你的config配置文件吗？  我下载你们的EFI后 里面的配置文件名字也修改了，可是修改后启动不了

### ISSUE THREAD

**Issue by 0703005** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#11]

**Comment by 0703005** [comment]
楼主你好，能分析下你的config文件吗？，你EFI文件里的这个[Sample.plist]改名后不行啊。

**Comment by Sky1058** [comment]
楼主你好,你EFI文件里的这个[Sample.plist]改名后不行啊,引导里不去。能否开的讨论组，

**Comment by Sky1058** [comment]
或者给个邮箱，请教点问题

**Comment by 0703005** [comment]
> 或者给个邮箱，请教点问题

你也进不去吗？  我的是复制[Sample.plist] 改名为config.plist添加sn后安装都进不去，估计给的这个plist 有问题，麻烦楼主能否给我发一份 你的配置文件  拜托了  413078904@QQ.com

**Comment by Sky1058** [comment]
我现在用别人的，但是有问题睡眠唤醒后自动重启




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月24日(星期五) 中午11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x] 你好能分享下你的config配置文件吗？  我下载你们的EFI后 里面的配置文件名字也修改了，可是修改后启动不了 (Issue #11)





  
或者给个邮箱，请教点问题
  
你也进不去吗？  我的是复制[Sample.plist] 改名为config.plist添加sn后安装都进不去，估计给的这个plist 有问题，麻烦楼主能否给我发一份 你的配置文件  拜托了  ***@***.***

**Comment by 0703005** [comment]
你的config文件能发我一份吗？

**Comment by DTR3912** [comment]
> > 或者给个邮箱，请教点问题
> 
> 你也进不去吗？ 我的是复制[Sample.plist] 改名为config.plist添加sn后安装都进不去，估计给的这个plist 有问题，麻烦楼主能否给我发一份 你的配置文件 拜托了 [413078904@QQ.com](mailto:413078904@QQ.com)

您好，我的经验是改名为config.plist启动后会有几行提示，进不去，用搜索引擎搜一下这几行提示会有解决方法，要在config.plist里改一下，我不记得具体内容了，您可以尝试一下。

**Comment by DTR3912** [comment]
> > 或者给个邮箱，请教点问题
> 
> 你也进不去吗？ 我的是复制[Sample.plist] 改名为config.plist添加sn后安装都进不去，估计给的这个plist 有问题，麻烦楼主能否给我发一份 你的配置文件 拜托了 [413078904@QQ.com](mailto:413078904@QQ.com)

您好，我的经验是改名为config.plist启动后会有几行提示，进不去，用搜索引擎搜一下这几行提示会有解决方法，要在config.plist里改一下，我不记得具体内容了，您可以尝试一下。

**Comment by DTR3912** [comment]
> > 或者给个邮箱，请教点问题
> 
> 你也进不去吗？ 我的是复制[Sample.plist] 改名为config.plist添加sn后安装都进不去，估计给的这个plist 有问题，麻烦楼主能否给我发一份 你的配置文件 拜托了 [413078904@QQ.com](mailto:413078904@QQ.com)

我把我改好的config.plist发给你了，你尝试一下。

**Comment by 0703005** [comment]
> > > 或者给个邮箱，请教点问题
> > 
> > 
> > 你也进不去吗？ 我的是复制[Sample.plist]改名为config.plist添加sn后安装都进不去，估计给的这个plist有问题，麻烦楼主要能不能给我发一个你文件 拜托了[413078904@QQ.com](mailto:413078904@QQ.com)
> 
> 我把我改好的config.plist发给你了，你试一下。

  我安装的能顺利安装，就是安装完毕不能进入界面（苹果走条走完后，就黑屏了，没动静了  咋弄？），你遇到没有？

**Comment by DTR3912** [comment]
> 

没有，但我遇到过一次卡进度条，强制重启了一次好了，不过我怕有问题又格盘重新安装了一遍，没卡进度条成功安装启动。

**Comment by DTR3912** [comment]
> > > > 或者给个邮箱，请教点问题
> > > 
> > > 
> > > 你也进不去吗？ 我的是复制[Sample.plist]改名为config.plist添加sn后安装都进不去，估计给的这个plist有问题，麻烦楼主要能不能给我发一个你文件 拜托了[413078904@QQ.com](mailto:413078904@QQ.com)
> > 
> > 
> > 我把我改好的config.plist发给你了，你试一下。
> 
> 我安装的能顺利安装，就是安装完毕不能进入界面（苹果走条走完后，就黑屏了，没动静了 咋弄？），你遇到没有？

没有，但我遇到过一次卡进度条，强制重启了一次好了，不过我怕有问题又格盘重新安装了一遍，没卡进度条成功安装启动。要是你没发现别的问题可以试一下重装。

**Comment by 0703005** [comment]
> > > > > 或者给个邮箱，请教点问题
> > > > 
> > > > 
> > > > 你也进不去吗？ 我的是复制[Sample.plist]改名为config.plist添加sn后安装都进不去，估计给的这个plist有问题，麻烦楼主要能不能给我发一个你文件 拜托了[413078904@QQ.com](mailto:413078904@QQ.com)
> > > 
> > > 
> > > 我把我改好的config.plist发给你了，你试一下。
> > 
> > 
> > 我安装的能顺利安装，就是安装完毕不能进入界面（苹果走条走完后，就黑屏了，没动静了 咋弄？），你遇到没有？
> 
> 没有，但我遇到过一次卡进度条，强制重启了一次好了，不过我怕有问题又格盘重新安装了一遍，没卡进度条成功安装启动。要是你没发现别的问题可以试一下重装。

你的m920x带独立显卡吗？

**Comment by DTR3912** [comment]
> > > > > > 或者给个邮箱，请教点问题
> > > > > 
> > > > > 
> > > > > 你也进不去吗？ 我的是复制[Sample.plist]改名为config.plist添加sn后安装都进不去，估计给的这个plist有问题，麻烦楼主要能不能给我发一个你文件 拜托了[413078904@QQ.com](mailto:413078904@QQ.com)
> > > > 
> > > > 
> > > > 我把我改好的config.plist发给你了，你试一下。
> > > 
> > > 
> > > 我安装的能顺利安装，就是安装完毕不能进入界面（苹果走条走完后，就黑屏了，没动静了 咋弄？），你遇到没有？
> > 
> > 
> > 没有，但我遇到过一次卡进度条，强制重启了一次好了，不过我怕有问题又格盘重新安装了一遍，没卡进度条成功安装启动。要是你没发现别的问题可以试一下重装。
> 
> 你的m920x带独立显卡吗？

带，我用的rx460，cpu是i7 8700t es

**Comment by chencaidy** [comment]
独显重启，大概率没关CFG Lock

**Comment by Sky1058** [comment]
集显 关了CFG Lock，但卡时度条。

**Comment by Sky1058** [comment]
配置
CPU:I5 9400
内存：DDR4 16G
硬盘：SN770 500G
显卡：集显
网卡：BCM94360CS2

**Comment by Sky1058** [comment]
集显关了CFG锁，但卡进度条

**Comment by chencaidy** [comment]
参考此Commit，将FB修改为3E9B0007或3E9B0000，并打端口补丁：
https://github.com/chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x/commit/1697fdf9e75ea260a47de3e0304c232f742423ab#diff-3a677859ccedc3dac652d637ef621dfb3cb207d5117f533671a6f4805d2df13a
卡进度条打开verbose模式，并且贴出log

**Comment by Sky1058** [comment]
> 参考此Commit，将FB修改为3E9B0007或3E9B0000，并打端口补丁：
> [1697fdf#diff-3a677859ccedc3dac652d637ef621dfb3cb207d5117f533671a6f4805d2df13a](https://github.com/chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x/commit/1697fdf9e75ea260a47de3e0304c232f742423ab#diff-3a677859ccedc3dac652d637ef621dfb3cb207d5117f533671a6f4805d2df13a)
> 卡进度条打开verbose模式，并且贴出log

![tempImageMJDenE](https://user-images.githubusercontent.com/126667302/228745898-d6226fb9-e63b-4d7b-904e-23ddc90d0e52.gif)
![tempImageIHJzMq](https://user-images.githubusercontent.com/126667302/228745988-d4455f10-d7f7-4f77-b781-cd50638196e1.gif)
![tempImageW6wl5k](https://user-imag
![tempImagek4DlSC](https://user-images.githubusercontent.com/126667302/228746187-81c0a57b-ee46-4d30-a6bb-91af968e627b.gif)
![tempImagedhRA0s](https://user-images.githubusercontent.com/126667302/228746246-39a474b6-6179-4d56-b66a-cc272a6530fc.gif)
![Uploading tempImageLU5JWp.gif…]()
es.githubusercontent.com/126667302/228746077-ea98c226-cae4-4d12-b33e-a718a4f25879.gif)

![tempImageXdeGYm](https://user-images.githubusercontent.com/126667302/228745948-00b231de-d71a-4345-bb38-8b0809b6f745.gif)
每次跑的都不一样

**Comment by chencaidy** [comment]
显卡可能没补丁正确，看看DeviceProperties部分

**Comment by chencaidy** [comment]
还有，不用去加alcid，igfxfw=2，不能进系统的情况加更不能先去开GuC，情况只会变得更糟

**Comment by 0703005** [comment]
我现在的是装好后 蓝牙不能用

**Comment by chencaidy** [comment]
> 我现在的是装好后 蓝牙不能用

检查USBPort是否注入正确，机型是否匹配

**Comment by ashllll** [comment]
> > 我现在的是装好后 蓝牙不能用
> 
> 检查USBPort是否注入正确，机型是否匹配

麻烦请教下大佬，您的网卡是安装在原来的M.2 NGFF插槽上的嘛？我的用转接版安装后只有蓝牙正常工作，wifi无法打开，usb以重新定制。
<img width="744" alt="image" src="https://github.com/chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x/assets/49464678/1d2a20a8-9eac-446a-8326-3a0dde7b9319">
<img width="999" alt="image" src="https://github.com/chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x/assets/49464678/893e8cc8-c211-43f8-8dbe-5acf9f98cd43">

**Comment by chencaidy** [comment]
> > > 我现在的是装好后 蓝牙不能用
> > 
> > 
> > 检查USBPort是否注入正确，机型是否匹配
> 
> 麻烦请教下大佬，您的网卡是安装在原来的M.2 NGFF插槽上的嘛？我的用转接版安装后只有蓝牙正常工作，wifi无法打开，usb以重新定制。 <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/49464678/294970205-1d2a20a8-9eac-446a-8326-3a0dde7b9319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTM4MzQsIm5iZiI6MTcwNDc5MzUzNCwicGF0aCI6Ii80OTQ2NDY3OC8yOTQ5NzAyMDUtMWQyYTIwYTgtOWVhYy00NDZhLTgzMjYtM2EwZGRlN2I5MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MjY4MTAxMDQ1NzNjNTkzNmI2NTAzNDZkN2I2NjE2OWViYmIwN2E2YjI3YmU3MjY5MGIxMmI1ZjA4MDFlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O4OyXGi39mzrP-j2rrhXwXvruP41BMVGQnlQEGAenIA"> <img alt="image" width="999" src="https://private-user-images.githubusercontent.com/49464678/294970281-893e8cc8-c211-43f8-8dbe-5acf9f98cd43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTM4MzQsIm5iZiI6MTcwNDc5MzUzNCwicGF0aCI6Ii80OTQ2NDY3OC8yOTQ5NzAyODEtODkzZThjYzgtYzIxMS00M2Y4LThkYmUtNWFjZjlmOThjZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNDE2ZDMwODM1M2I5NzM4MzMyZWUzNjI2MTZhMGExMmMxZWZiMzU4NWQ3MThkODQwYzQwYjVhZDNlNjkyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SC-UC9fB9Fh1n_VsD9m2gf2OO--QsF13ynapUeQEJBo">

系统是sonoma？尝试dev-sonoma分支

**Comment by ashllll** [comment]
> > > > 我现在的是装好后 蓝牙不能用
> > > 
> > > 
> > > 检查USBPort是否注入正确，机型是否匹配
> > 
> > 
> > 麻烦请教下大佬，您的网卡是安装在原来的M.2 NGFF插槽上的嘛？我的用转接版安装后只有蓝牙正常工作，wifi无法打开，usb以重新定制。 <img alt="image" width="744" src="https://private-user-images.githubusercontent.com/49464678/294970205-1d2a20a8-9eac-446a-8326-3a0dde7b9319.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTM4MzQsIm5iZiI6MTcwNDc5MzUzNCwicGF0aCI6Ii80OTQ2NDY3OC8yOTQ5NzAyMDUtMWQyYTIwYTgtOWVhYy00NDZhLTgzMjYtM2EwZGRlN2I5MzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MjY4MTAxMDQ1NzNjNTkzNmI2NTAzNDZkN2I2NjE2OWViYmIwN2E2YjI3YmU3MjY5MGIxMmI1ZjA4MDFlZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O4OyXGi39mzrP-j2rrhXwXvruP41BMVGQnlQEGAenIA"> <img alt="image" width="999" src="https://private-user-images.githubusercontent.com/49464678/294970281-893e8cc8-c211-43f8-8dbe-5acf9f98cd43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3OTM4MzQsIm5iZiI6MTcwNDc5MzUzNCwicGF0aCI6Ii80OTQ2NDY3OC8yOTQ5NzAyODEtODkzZThjYzgtYzIxMS00M2Y4LThkYmUtNWFjZjlmOThjZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA5NDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNDE2ZDMwODM1M2I5NzM4MzMyZWUzNjI2MTZhMGExMmMxZWZiMzU4NWQ3MThkODQwYzQwYjVhZDNlNjkyZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SC-UC9fB9Fh1n_VsD9m2gf2OO--QsF13ynapUeQEJBo">
> 
> 系统是sonoma？尝试dev-sonoma分支

系统是Ventura 13.6.3
