### ISSUE TITLE
请教下大佬cfg lock是怎么找到的

### ISSUE THREAD

**Issue by 1pcr3ss** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#12]
UEFITool打开M1UJY70USA解压出来的imageM1U.ROM，搜索cfg没有结果。
另外试了下打开M1AJY56USA和用fptw64备份出来的也搜不到。
![image](https://user-images.githubusercontent.com/13669961/227771804-325c4bea-9774-4669-9e55-b14b10317b8b.jpg)

**Comment by 0703005** [comment]
这个要在安装的时候 手动输这个命令。进入到安装界面的时候，  不是刷bios，也不是设置bios界面。

**Comment by 1pcr3ss** [comment]
> 这个要在安装的时候 手动输这个命令。进入到安装界面的时候， 不是刷bios，也不是设置bios界面。

不是，我想问的是怎么找到的这个地址。

**Comment by chencaidy** [comment]
提取Setup FFS模块，使用IRFExtractor解析为文本

**Comment by 1pcr3ss** [comment]
换了个uefitool能搜到cfg lock了。。。OvO
