### ISSUE TITLE
sonoma14 可以驱动BCM网卡的

### ISSUE THREAD

**Issue by fyjsy** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#17]
https://osx.cx/macos-sonoma-14-drive-broadcom.html

**Comment by chencaidy** [comment]
已经测试适配，可以参考 dev-sonoma 分支
https://github.com/chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x/tree/dev-sonoma
