### ISSUE TITLE
同样是M920X但是使用EFI会加重启

### ISSUE THREAD

**Issue by MikuMaxZ** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#19]
同样是M920X但是没有显卡
其他配置是一样
使用EFI会加载到四分之一会重启

**Comment by chencaidy** [comment]
把独显开启并在BIOS设置64M DVMT
参考这一次的更新https://github.com/chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x/commit/1697fdf9e75ea260a47de3e0304c232f742423ab#diff-3a677859ccedc3dac652d637ef621dfb3cb207d5117f533671a6f4805d2df13a
