### ISSUE TITLE
请教一下替换EFI的问题

### ISSUE THREAD

**Issue by 101633736** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#4]
我现在下载的是黑果小兵的3分区安装镜像，是否需要全部替换您的EFI到 U盘镜像的EFI？

**Comment by chencaidy** [comment]
需要把Sample.plist重命名并且重新生成MLB和序列号

**Comment by 101633736** [comment]
删除了小兵的EFI 完全替换成你的 就进不去oc开机的引导界面了....不知要需要具体替换哪个文件夹，然后还有就是黑果界面异常的卡顿， 没法正确驱动核显之类的...感觉CPU也降频了。。。我VX是a101633736 希望能得到您的帮助。。。

**Comment by 101633736** [comment]
删除了小兵的EFI完全替换成您的EFI就进不去OC引导界面了。...不知道具体需要替换哪个文件夹，然后就是黑果异常的卡顿，无法驱动核显之类的...感觉CPU也降频了。。。我VX是a101633736，希望能得到您的帮助。。。

**Comment by 101633736** [comment]
> 
哎 理解您的不方便，想问下如何重命名sample.plist 和重新生成MLB和序列号。。。

**Comment by chencaidy** [comment]
https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#platforminfo

**Comment by 101633736** [comment]
收到 很感谢 我先学习一下
