### ISSUE TITLE
请教关闭CFG Lock

### ISSUE THREAD

**Issue by lolo-zhou** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#5]
您好，不太明白这个如何关闭？能有详细步骤指导吗？感谢

**Comment by chencaidy** [comment]
参考https://rmtt.gitbook.io/opencore-vanilla-guide/bu-chong/xiu-fu-cfg-lock
或者把config.plist的AppleCpuPmCfgLock和AppleXcpmCfgLock字段置为true

**Comment by lolo-zhou** [comment]
感谢指导；摸索了几天，明白怎么操作了
