### ISSUE TITLE
请教一下DRM的问题

### ISSUE THREAD

**Issue by LJAYi** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#6]
感谢您的付出。我的机器用的是您最新的EFI，运行状态良好！

请教一下DRM的问题，我尝试在12.3系统下添加shikigva=80（只在12.3版本下测试过），启动属性和设备属性的添加方式都尝试过，并没有起到作用，Apple music还是会跳歌，Apple tv无法播放。配置只有CPU不一样，是8700T。烦请指点一二～

**Comment by chencaidy** [comment]
https://dortania.github.io/OpenCore-Post-Install/universal/drm.html
根据此文档，如果你没有一张外置显卡（如RX560），从10.12.3开始DRM就已经损坏
因为黑果没有签名证书

**Comment by LJAYi** [comment]
是的，我和您的GPU配置一样，有一张外置显卡（RX560）。但是我按照文档添加shikigva=80，并没有修复DRM🥲
想询问您是否根据此文档成功修复DRM
