### ISSUE TITLE
请教一下只有核显没有独显怎么改？

### ISSUE THREAD

**Issue by fyjsy** [chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x#7]
看到您更新里提到改成了独立显卡，我没有独显请问需要怎么改？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by chencaidy** [comment]
参考此Commit，将FB修改为3E9B0007，并打端口补丁：
https://github.com/chencaidy/Hackintosh-OC-Lenovo-ThinkCentre-M920x/commit/1697fdf9e75ea260a47de3e0304c232f742423ab#diff-3a677859ccedc3dac652d637ef621dfb3cb207d5117f533671a6f4805d2df13a

**Comment by sdholloo** [comment]
将FB修改为3E9B0007以后，能够开机，但是显存显示只有7M，而且显示卡顿，大佬能否出一个专门的没有独显的efi

**Comment by chencaidy** [comment]
提供详细的配置

**Comment by sdholloo** [comment]
M920x
i5 8500
sn750 256
sumsung 8+8

**Comment by sdholloo** [comment]
我有一个vga的扩展口，我的显示器是vga的，插在vga上，不知道会不会有影响

**Comment by chencaidy** [comment]
设备无兼容问题，贴出修改后的config.plist看看

**Comment by Sky1058** [comment]
M920x
CPU:i5 9400
硬盘：sn770 500G
内存：金士顿DDR4 2666 16G
网卡:bcm94360cs2
问题，进不去引导.能否指导一下，谢谢！328223360@qq.com
